logger: 'console'
log: 'debug'
appname: "zeroconf"
charset: "UTF-8"
serializer: YAML
logger_format: %{%H:%M %Y-%m-%d}t: %m in %f l. %l


myName: zeroconfService
myToken: token
avahiScanFrequency: 20
workerPeriod: 200


unitIdentifiers:
        sensor: '_nufw._tcp' 
        master: '_islc._tcp'
        action: '_venus._tcp'
        processor: '_topx._tcp'
        ui: '_unicontrol._tcp'
        data: '_netangel._tcp'
        log: '_integral._tcp'
        avahi: '_krb524._udp'

unitTypesToTrack:
  - sensor
  - master
  - action
  - processor
  - avahi

# this is to form the first part of a link when accessing a given type of a service
serviceTypeLinks:
        master: masters
        action: actions


serviceTypesToOfferService:
        - master
        - action


