logger: 'console'
log: 'debug'
appname: "master"
charset: "UTF-8"
serializer: YAML

sensorService: '_nufw._tcp'
masterService: '_islc._tcp'
actionService: '_venus._tcp'
processorService: '_topx._tcp'
uiService: '_unicontrol._tcp'
dataService: '_netangel._tcp'
logService: '_integral._tcp'
avahiService: '_krb524._udp'

sensorsUpdateFrequency: 5
subscribedSensorsTrackingFrequency: 10
masterAvahiName: Master1
masterName: Master1
masterToken: passToSensor

logicServicesSearchingFrequency: 5
logicServicesTrackingFrequency: 7
workerPeriod: 200

#I am interested only in those sensors
trackedSensors:
  - TestSensor
  - SoundCardSensor
  - UserHomeWifi

myLogicServices:
        - logicService1

logicServicesTokens:
  logicService1: password


#Sensors have to give me those credentials
knownSensors:
  - TestSensor
  - SoundCardSensor
  - UserHomeWifi

sensorsTokens:
  SoundCardSensor: token
  UserHomeWifi: token
  TestSensor: token

#action users (processors) have to give me those credentials
knownActionUsers:
  - logicService1
  - actionService

actionUsersTokens:
  logicService1: password
  actionService: password


#I  provide actions with those credentials
actionsCredentials:
  TestAction: passToAction
  SwitchAmpOn: passToAction
  SwitchAmpOff: passToAction
  SetRysiekVolume: passToAction
  PlaySongOnRysiekMpd: passToAction
  AlarmClock: passToAction
