logger: 'console'
log: 'debug'
appname: "master"
charset: "UTF-8"
serializer: YAML
logger_format: %{%H:%M %Y-%m-%d}t: %m in %f l. %l

sensorService: 'sensor'
masterService: 'master'
actionService: 'action'
processorService: 'processor'
uiService: 'ui'
dataService: 'data'
logService: 'log'
avahiService: 'avahi'

sensorsUpdateFrequency: 5
masterAvahiName: Master1
masterAvahiType: '_islc._tcp'
masterName: Master1
masterToken: passToSensor

logicServicesSearchingFrequency: 5
logicServicesTrackingFrequency: 7
workerPeriod: 200

#I am interested only in those sensors
trackedSensors:
  - TestSensor
  - SoundCardSensor
  - UserHomeWifi

myLogicServices:
        - logicService1

logicServicesTokens:
  logicService1: password


#Sensors have to give me those credentials
knownSensors:
  - TestSensor
  - SoundCardSensor
  - UserHomeWifi

sensorsTokens:
  SoundCardSensor: token
  UserHomeWifi: token
  TestSensor: token

#action users (processors) have to give me those credentials
knownActionUsers:
  - logicService1
  - actionService

actionUsersTokens:
  logicService1: password
  actionService: password

knownZeroconfs:
  - zeroconfService

zeroconfTokens:
  zeroconfService: token


#I  provide actions with those credentials
actionsCredentials:
  TestAction: passToAction
  SwitchAmpOn: passToAction
  SwitchAmpOff: passToAction
  SetRysiekVolume: passToAction
  PlaySongOnRysiekMpd: passToAction
  AlarmClock: passToAction
