logger: 'console'
log: 'debug'
appname: "actions"
charset: "UTF-8"
serializer: YAML

unitIdentifiers:
        sensor: '_nufw._tcp' 
        master: '_islc._tcp'
        action: '_venus._tcp'
        processor: '_topx._tcp'
        ui: '_unicontrol._tcp'
        data: '_netangel._tcp'
        log: '_integral._tcp'
        avahi: '_krb524._udp'

wemoDb: '/tmp/wemo.db'
wemoAmpName: rysiek

#when actions need to fire another actions, they need to go through Master
actionUserLogin: actionService
actionUserPassword: password

masterTrackingInterval: 5
