logger: 'console'
log: 'debug'
appname: "actions"
charset: "UTF-8"
serializer: YAML
logger_format: %{%H:%M %Y-%m-%d}t: %m in %f l. %l
actionServiceAvahiType: _venus._tcp

wemoDb: '/tmp/wemo.db'
wemoAmpName: rysiek

#when actions need to fire another actions, they need to go through Master
actionUserLogin: actionService
actionUserPassword: password

masterTrackingInterval: 5
workerPeriod: 200

masterService: 'master'

knownZeroconfs:
  - zeroconfService

zeroconfTokens:
  zeroconfService: token


